if [ ! -f "$HOME/.dotfiles-location" ]; then
    echo "ERROR: $HOME/.dotfiles-location not found."
    echo "       This needs to be a file that exports DOTFILES_DIR, the location"
    echo "       of your dotfiles (https://github.com/edwinbalani/dotfiles.git)"
    echo "         e.g. echo 'export DOTFILES_DIR=\$HOME/dotfiles' > ~/.dotfiles-location"
elif [ ! -d "$HOME/.antidote" ]; then
    echo "ERROR: Antidote installation not found at ~/.antidote"
    echo "       Run "
    echo "           git clone  https://github.com/mattmc3/antidote.git ~/.antidote"
    echo "       to fix."
else
    source "$HOME/.dotfiles-location"  # exports DOTFILES_DIR
    source "$DOTFILES_DIR/util.sh"

    # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
    # Initialization code that may require console input (password prompts, [y/n]
    # confirmations, etc.) must go above this block; everything else may go below.
    if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
        source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
    fi

    for component in export alias function; do
        source "$DOTFILES_DIR/shell/$component.sh"
    done
    for component in powerlevel10k antidote fzf misc; do
        source "$DOTFILES_DIR/zsh/$component.zsh"
    done
    if [ -f "$HOME/.zshrc.local" ]; then
        source "$HOME/.zshrc.local"
    fi
fi
