# file and folder manipulation
alias md='mkdir -p'
alias rd=rmdir

# try not to destroy the filesystem
alias cp='cp -i'
alias rm='rm -i'
alias mv='mv -i'

# ls, du
alias l='ls -lFh'
alias lS='ls -1FSsh'
alias la='ls -lAFh'
alias lart='ls -1Fcart'
alias ldot='ls -ld .*'
alias ll='ls -l'
alias lr='ls -tRFh'
alias lrt='ls -1Fcrt'
alias ls='ls --color=tty'
alias lsa='ls -lah'
alias lt='ls -ltFh'
alias dud='du -d 1 -h'
alias duf='du -sh *'

# grep, find (and do stuff, sometimes)
alias grep='grep --color'
alias sgrep='grep -R -n -H -C 5 --exclude-dir={.git,.svn,CVS} '
alias fd='find . -type d -name'
alias ff='find . -type f -name'
alias set644='find . -type f ! -perm 644 -print0 | xargs -0 chmod 644'
alias set755='find . -type d ! -perm 755 -print0 | xargs -0 chmod 755'

# Python
alias pyfind='find . -name "*.py"'
alias pygrep='grep --include="*.py"'
alias pylint-quick='pylint --reports=n'

# misc.
alias d='dirs -v | head -10'
alias p='ps -f'
alias d64=decode64
alias e64=encode64
alias sortnr='sort -n -r'
alias t='tail -f'
alias afind='ack -il'
alias unexport=unset

# professionalism
alias please=sudo

# Git. Lots of it.
alias g=git
alias ga='git add'
alias gaa='git add --all'
alias gap='git apply'
alias gapa='git add --patch'
alias gau='git add --update'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gbda='git branch --no-color --merged | command grep -vE "^(\*|\s*(master|develop|dev)\s*$)" | command xargs -n 1 git branch -d'
alias gbl='git blame -b -w'
alias gbnm='git branch --no-merged'
alias gbr='git branch --remote'
alias gbs='git bisect'
alias gbsb='git bisect bad'
alias gbsg='git bisect good'
alias gbsr='git bisect reset'
alias gbss='git bisect start'
alias gc='git commit -v'
alias 'gc!'='git commit -v --amend'
alias gca='git commit -v -a'
alias 'gca!'='git commit -v -a --amend'
alias gcam='git commit -a -m'
alias 'gcan!'='git commit -v -a --no-edit --amend'
alias 'gcans!'='git commit -v -a -s --no-edit --amend'
alias gcb='git checkout -b'
alias gcd='git checkout develop'
alias gcf='git config --list'
alias gcl='git clone --recursive'
alias gclean='git clean -fd'
alias gcm='git checkout master'
alias gcmsg='git commit -m'
alias 'gcn!'='git commit -v --no-edit --amend'
alias gco='git checkout'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'
alias gcs='git commit -S'
alias gcsm='git commit -s -m'
alias gd='git diff'
alias gdca='git diff --cached'
alias gdct='git describe --tags `git rev-list --tags --max-count=1`'
alias gdcw='git diff --cached --word-diff'
alias gdt='git diff-tree --no-commit-id --name-only -r'
alias gdw='git diff --word-diff'
alias gf='git fetch'
alias gfa='git fetch --all --prune'
alias gfo='git fetch origin'
alias gg='git gui citool'
alias gga='git gui citool --amend'
alias ggpull='git pull origin $(git_current_branch)'
alias ggpur=ggu
alias ggpush='git push origin $(git_current_branch)'
alias ggsup='git branch --set-upstream-to=origin/$(git_current_branch)'
alias ghh='git help'
alias gignore='git update-index --assume-unchanged'
alias gignored='git ls-files -v | grep "^[[:lower:]]"'
alias git-svn-dcommit-push='git svn dcommit && git push github master:svntrunk'
alias gk='\gitk --all --branches'
alias gke='\gitk --all $(git log -g --pretty=%h)'
alias gl='git pull'
alias glg='git log --stat'
alias glgg='git log --graph'
alias glgga='git log --graph --decorate --all'
alias glgm='git log --graph --max-count=10'
alias glgp='git log --stat -p'
alias glo='git log --oneline --decorate'
alias glog='git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'
alias glol='git log --graph --pretty='\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --abbrev-commit'
alias glola='git log --graph --pretty='\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --abbrev-commit --all'
alias glum='git pull upstream master'
alias gm='git merge'
alias gma='git merge --abort'
alias gmom='git merge origin/master'
alias gmt='git mergetool --no-prompt'
alias gmtvim='git mergetool --no-prompt --tool=vimdiff'
alias gmum='git merge upstream/master'
alias gp='git push'
alias gpd='git push --dry-run'
alias gpoat='git push origin --all && git push origin --tags'
alias gpristine='git reset --hard && git clean -dfx'
alias gpsup='git push --set-upstream origin $(git_current_branch)'
alias gpu='git push upstream'
alias gpv='git push -v'
alias gr='git remote'
alias gra='git remote add'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase -i'
alias grbm='git rebase master'
alias grbs='git rebase --skip'
alias grh='git reset HEAD'
alias grhh='git reset HEAD --hard'
alias grmv='git remote rename'
alias grrm='git remote remove'
alias grset='git remote set-url'
alias grt='cd $(git rev-parse --show-toplevel || echo ".")'
alias gru='git reset --'
alias grup='git remote update'
alias grv='git remote -v'
alias gsb='git status -sb'
alias gsd='git svn dcommit'
alias gsi='git submodule init'
alias gsps='git show --pretty=short --show-signature'
alias gsr='git svn rebase'
alias gss='git status -s'
alias gst='git status'
alias gsta='git stash save'
alias gstaa='git stash apply'
alias gstc='git stash clear'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash show --text'
alias gsu='git submodule update'
alias gts='git tag -s'
alias gtv='git tag | sort -V'
alias gunignore='git update-index --no-assume-unchanged'
alias gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
alias gup='git pull --rebase'
alias gupv='git pull --rebase -v'
alias gwch='git whatchanged -p --abbrev-commit --pretty=medium'
alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify -m "--wip-- [skip ci]"'

# shell wizardry
alias h=history
alias hgrep='fc -El 0 | grep'
alias history='fc -l 1'
alias hsi='hs -i'
alias po=popd
alias pu=pushd

# systemctl
# SOME OF THESE ALIASES INVOKE SUDO.  Be careful out there.
alias sc-cancel='sudo systemctl cancel'
alias sc-cat='systemctl cat'
alias sc-disable='sudo systemctl disable'
alias sc-disable-now='sc-disable --now'
alias sc-edit='sudo systemctl edit'
alias sc-enable='sudo systemctl enable'
alias sc-enable-now='sc-enable --now'
alias sc-help='systemctl help'
alias sc-is-active='systemctl is-active'
alias sc-is-enabled='systemctl is-enabled'
alias sc-isolate='sudo systemctl isolate'
alias sc-kill='sudo systemctl kill'
alias sc-link='sudo systemctl link'
alias sc-list-jobs='systemctl list-jobs'
alias sc-list-timers='systemctl list-timers'
alias sc-list-unit-files='systemctl list-unit-files'
alias sc-list-units='systemctl list-units'
alias sc-load='sudo systemctl load'
alias sc-mask='sudo systemctl mask'
alias sc-mask-now='sc-mask --now'
alias sc-preset='sudo systemctl preset'
alias sc-reenable='sudo systemctl reenable'
alias sc-reload='sudo systemctl reload'
alias sc-reset-failed='sudo systemctl reset-failed'
alias sc-restart='sudo systemctl restart'
alias sc-set-environment='sudo systemctl set-environment'
alias sc-show='systemctl show'
alias sc-show-environment='systemctl show-environment'
alias sc-start='sudo systemctl start'
alias sc-status='systemctl status'
alias sc-stop='sudo systemctl stop'
alias sc-try-restart='sudo systemctl try-restart'
alias sc-unmask='sudo systemctl unmask'
alias sc-unset-environment='sudo systemctl unset-environment'
